name: Deploy
on:
  push:
    banches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '12.x'
          registry-url: https://registry.npmjs.org
      - name: Install deps
        run: npm ci
      - name: Build...
        run: npm build
      - name: Release
        run: npx semantic-release@17
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
